#!/bin/bash
# ============================================================================
# SeqLoRA Continual VQA Training: ScienceQA → TextVQA → VizWiz
# With image captions injected into prompts for long-text capability testing.
#
# Uses caption-augmented train data: train_data_with_caption.jsonl
# Generated by add_captions.py
#
# Three-stage pipeline per task:
#   Stage 1: LoRA fine-tuning  → adapter checkpoint
#   Stage 2: Merge LoRA        → full HF model
#   Stage 3: Convert HF→Chameleon (optional, for native inference)
#
# Usage:
#   cd /data1/data/kangborui/zhongyukun/medmax/medmax
#   bash run_seqlora_sci_text_vizwiz.sh
# ============================================================================

set -e

# ── Paths ──────────────────────────────────────────────────────────────
BASE_DIR="/data1/data/kangborui/zhongyukun/medmax"
MEDMAX_DIR="${BASE_DIR}/medmax"
DATA_DIR="${BASE_DIR}/MoDE-official/data"
ANOLE_HF="${BASE_DIR}/anole_7b_hf"
ANOLE_ORIG="${BASE_DIR}/Anole-7b-v0.1"
DS_CONFIG="${MEDMAX_DIR}/training/ds_config.json"

OUTPUT_BASE="${BASE_DIR}/output_dir_seqLoRA_Sci_Text_VizWiz_caption"

# ── Hyperparameters (match existing SeqLoRA runs) ──────────────────────
LORA_R=8
LR=1e-4
EPOCH=1
BS=1
LR_SCHEDULER="cosine"
WARMUP_RATIO=0.1
SAVE_STRATEGY="steps"
GPUS="2"
NUM_GPUS=1

# ── Task order ─────────────────────────────────────────────────────────
TASKS=("scienceqa" "textvqa" "vizwiz")
TASK_DIRS=("ScienceQA" "TextVQA" "VizWiz")

cd "${MEDMAX_DIR}"

echo "============================================================"
echo " SeqLoRA Continual VQA: ScienceQA → TextVQA → VizWiz"
echo " With caption-augmented prompts (max_length=${MAX_LENGTH})"
echo " Output: ${OUTPUT_BASE}"
echo "============================================================"

PREV_CKPT="${ANOLE_HF}"

for i in "${!TASKS[@]}"; do
    TASK="${TASKS[$i]}"
    TASK_DIR="${TASK_DIRS[$i]}"
    TRAIN_DATA="${DATA_DIR}/${TASK_DIR}/train_data_with_caption.jsonl"

    STAGE1_DIR="${OUTPUT_BASE}/seqlora_${TASK}/seqlora_${TASK}_stage1"
    STAGE2_DIR="${OUTPUT_BASE}/seqlora_${TASK}/seqlora_${TASK}_stage2"
    STAGE3_DIR="${OUTPUT_BASE}/seqlora_${TASK}/seqlora_${TASK}_stage3"

    echo ""
    echo "============================================================"
    echo " Task $((i+1))/${#TASKS[@]}: ${TASK}"
    echo "   Train data: ${TRAIN_DATA}"
    echo "   Base model: ${PREV_CKPT}"
    echo "============================================================"

    # ── Stage 1: LoRA fine-tuning ──────────────────────────────────────
    if [ ! -d "${STAGE1_DIR}" ] || [ -z "$(ls -A ${STAGE1_DIR}/checkpoint-* 2>/dev/null)" ]; then
        echo "[Stage 1] LoRA training for ${TASK}..."
        CUDA_VISIBLE_DEVICES=${GPUS} torchrun --nproc_per_node=${NUM_GPUS} \
            -m training.train \
            --train_data "${TRAIN_DATA}" \
            --ckpt "${PREV_CKPT}" \
            --ds "${DS_CONFIG}" \
            --output_dir "${STAGE1_DIR}" \
            --epoch ${EPOCH} \
            --bs ${BS} \
            --lora \
            --lora_r ${LORA_R} \
            --lr ${LR} \
            --lr_scheduler ${LR_SCHEDULER} \
            --warmup_ratio ${WARMUP_RATIO} \
            --save_strategy ${SAVE_STRATEGY}
        echo "[Stage 1] Done: ${STAGE1_DIR}"
    else
        echo "[Stage 1] Already exists, skipping."
    fi

    # Find the last checkpoint
    LAST_CKPT=$(ls -d ${STAGE1_DIR}/checkpoint-* 2>/dev/null | sort -t- -k2 -n | tail -1)
    if [ -z "${LAST_CKPT}" ]; then
        echo "ERROR: No checkpoint found in ${STAGE1_DIR}" >&2
        exit 1
    fi
    echo "  Using checkpoint: ${LAST_CKPT}"

    # ── Stage 2: Merge LoRA into base model ────────────────────────────
    if [ ! -d "${STAGE2_DIR}" ] || [ ! -f "${STAGE2_DIR}/config.json" ]; then
        echo "[Stage 2] Merging LoRA adapter for ${TASK}..."
        CUDA_VISIBLE_DEVICES=0 python -m src.load_lora_and_merge \
            --ckpt_path "${LAST_CKPT}" \
            --base_path "${PREV_CKPT}" \
            --output_dir "${STAGE2_DIR}"
        # Copy tokenizer files to merged model directory
        for f in tokenizer.json tokenizer_config.json special_tokens_map.json preprocessor_config.json; do
            if [ -f "${ANOLE_HF}/${f}" ] && [ ! -f "${STAGE2_DIR}/${f}" ]; then
                cp "${ANOLE_HF}/${f}" "${STAGE2_DIR}/"
            fi
        done
        echo "[Stage 2] Done: ${STAGE2_DIR}"
    else
        echo "[Stage 2] Already exists, skipping."
    fi

    # ── Stage 3: Convert HF → Chameleon format (optional) ─────────────
    if [ ! -d "${STAGE3_DIR}" ]; then
        echo "[Stage 3] Converting to Chameleon format for ${TASK}..."
        CUDA_VISIBLE_DEVICES=0 python -m src.bin_to_pth \
            --trained_ckpt "${STAGE2_DIR}" \
            --original_ckpt "${ANOLE_ORIG}" \
            --new_ckpt "${STAGE3_DIR}"
        echo "[Stage 3] Done: ${STAGE3_DIR}"
    else
        echo "[Stage 3] Already exists, skipping."
    fi

    # Next task uses this task's merged model as base
    PREV_CKPT="${STAGE2_DIR}"
done

echo ""
echo "============================================================"
echo " All tasks completed!"
echo " Output directory: ${OUTPUT_BASE}"
echo "============================================================"
echo ""
echo "To evaluate, run:"
echo "  cd ${MEDMAX_DIR}"
echo "  CUDA_VISIBLE_DEVICES=0 python -m evaluation.run_continual_vqa_eval \\"
echo "    --model_base_dir ${OUTPUT_BASE} \\"
echo "    --image_base_dir ${BASE_DIR}/coin_raw \\"
echo "    --data_base_dir ${BASE_DIR}/MoDE-official \\"
echo "    --output_dir ${OUTPUT_BASE}/continual_eval_results \\"
echo "    --model_format hf \\"
echo "    --hf_base_model_dir ${ANOLE_HF} \\"
echo "    --task_order scienceqa textvqa vizwiz"
